name: practice_riverpod
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-231.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.9
  http: ^0.13.5
  intl: ^0.18.0
  riverpod_annotation: ^1.2.1
  simple_logger: ^1.9.0+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true
